#!/bin/sh

[[ ! -f .git/config ]] && echo ".git/config not found - can't set credentials" && exit 1

is_mpab=$(cat .git/config | grep url | grep mpab)
is_asrai=$(cat .git/config | grep url | grep asrai)
is_covario=$(cat .git/config | grep url | grep covario)

if [ -n "$is_mpab" ]; then
    echo "repo: mpab"
    git config user.name mpab
    git config user.email mick_bythell@hotmail.com
elif [ -n "$is_asrai" ]; then
    echo "repo: asrai"
    git config user.name archangel
    git config user.email archangel@asrai.io
elif [ -n "$is_covario" ]; then
    echo "repo: covario"
    git config user.name archangel
    git config user.email michael.alderson-bythell@covar.io
else
    echo "repo: ???"
    exit 1
fi

git config user.name
git config user.email
