#!/bin/sh

[[ ! -f .git/config ]] && echo ".git/config not found - can't set credentials" && exit 1

is_mpab=$(cat .git/config | grep url | grep mpab)
is_asrai=$(cat .git/config | grep url | grep asrai)

if [ -n "$is_mpab" ]; then
    echo "repo: mpab"
    git config user.name mpab
    git config user.email mick_bythell@hotmail.com
    export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_github_mpab'
elif [ -n "$is_asrai" ]; then
    echo "repo: asrai"
    git config user.name archangel
    git config user.email archangel@asrai.io
    export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_github_asrai'
else
    echo "repo: ???"
    exit 1
fi

git config user.name
git config user.email
