#!/bin/sh

if [ -z $1 ]; then
    echo usage: $0 directory
    exit 1
fi

if [ ! -d $1 ]; then
    echo usage: $0 $1 - $1 is not a directory
    exit 1
fi

files=$(ls $1)

for file in $files; do
    filepath=$1/$file
    if [ -e $filepath ] &&  [ ! -d $filepath ] && [ -f $filepath ]; then
        echo making file $filepath executable
        chmod +x $filepath
        dos2unix $filepath
    fi
done
