#!/bin/bash

if [ "$1"x == "x" ]; then
  echo error: missing folder_name argument
  echo usage: $0 folder_name file_name
  exit
fi

if [ "$2"x == "x" ]; then
  echo error: missing file_name argument
  echo usage: $0 folder_name file_name
  exit
fi

# assign in order of least favourite
[[ $(which vi) != *"not found"* && $(which vi) != "" ]] && EDITOR=vi
[[ $(which vim) != *"not found"* && $(which vim) != "" ]] && EDITOR=vim
[[ $(which nano) != *"not found"* && $(which nano) != "" ]] && EDITOR=nano
[[ $(which code) != *"not found"* && $(which code) != "" ]] && EDITOR=code

[[ -z $EDITOR ]] && echo no text editor found && exit

for FILE in $(ls $1)
do
  if [ "$2"x == "$FILE"x ]; then
    $EDITOR $1/$2
    exit
  fi
done

echo $2 not found